# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Prompt Format
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$git_commit\
$fill\
$python\
$lua\
$nodejs\
$golang\
$haskell\
$rust\
$ruby\
$aws\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""

add_newline = true
palette = "nord"

[character]
success_symbol = "[\\$](bold fg:green)"
error_symbol = "[\\$](bold fg:red)"

# username
[username]
style_user = "bold fg:purple"
format = "[$user]($style)"
show_always = true

# hostname
[hostname]
style = "bold fg:green"
format = "[@](white bold)[$hostname](bold fg:green)[:](orange bold)[ ](orange bold)"
ssh_only = false

# Directory
[directory]
style = "bold fg:dark_blue"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = " "
"Music" = " "
"Pictures" = " "

# Git Branch
[git_branch]
style = "fg:green"
symbol = " "
format = "[on](white) [$symbol$branch ]($style)"

# Git Status
[git_status]
style = "fg:red"
format = "([$all_status$ahead_behind]($style) )"

# Spacer
[fill]
symbol = " "
style = "none"

# Python
[python]
style = "teal"
symbol = " "
format = "[${symbol}${pyenv_prefix}(${version} )(($virtualenv) )]($style)"
pyenv_version_name = true
pyenv_prefix = ""

# Lua
[lua]
format = "[$symbol($version )]($style)"
symbol = " "

# Node.js
[nodejs]
style = "blue"
symbol = " "

# Go
[golang]
style = "blue"
symbol = " "

# Haskell
[haskell]
style = "blue"
symbol = " "

# Rust
[rust]
style = "orange"
symbol = " "

# Ruby
[ruby]
style = "blue"
symbol = " "

# Package
[package]
symbol = "󰏗 "

# AWS
[aws]
symbol = " "
style = "yellow"
format = "[$symbol$profile]($style) [$duration]($style)"

# Docker
[docker_context]
symbol = " "
style = "fg:#06969A"
format = "[$symbol]($style) $path"
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_extensions = ["Dockerfile"]

# Background Jobs
[jobs]
symbol = " "
style = "red"
number_threshold = 1
format = "[$symbol]($style)"

# Command Duration
[cmd_duration]
min_time = 500
style = "fg:gray"
format = "[$duration]($style)"

# Palette: Nord
[palettes.nord]
dark_blue = "#5E81AC"
blue = "#81A1C1"
teal = "#88C0D0"
red = "#BF616A"
orange = "#D08770"
green = "#A3BE8C"
yellow = "#EBCB8B"
purple = "#B48EAD"
gray = "#434C5E"
black = "#2E3440"
white = "#D8DEE9"


